### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#107]
从代码中可以看到，当前的实现是通过检查版本号来判断是 KV v1 引擎:

```
{{- if eq (int $.version) 1 }}
  {{ $key }}: {{ "{{" }} index .Data "{{ $value }}" {{ "}}" }}
{{- else }}
  {{ $key }}: {{ "{{" }} index .Data.data "{{ $value }}" {{ "}}" }}
{{- end }}
```

要支持 KV v2 引擎，我们需要修改判断逻辑，因为 KV v2 的数据结构与 v1 不同。在 v2 中，数据存储在 `data.data` 路径下。我建议这样修改:

```
{{- define "vault.secrets" -}}
{{- range $key, $value := .config.secrets }}
{{- if eq (int $.version) 1 }}
  {{ $key }}: {{ "{{" }} index .Data "{{ $value }}" {{ "}}" }}
{{- else if eq (int $.version) 2 }}
  {{ $key }}: {{ "{{" }} index .Data.data "{{ $value }}" {{ "}}" }}
{{- else }}
  {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." }}
{{- end }}
{{- end }}
{{- end }}
```

主要改动点:
1. 将 else 分支改为明确的 `else if eq (int $.version) 2`
2. 添加一个 else 分支来处理不支持的版本号
3. 对 v2 引擎使用 `.Data.data` 路径来获取数据

同时，你可能还需要修改相关的 secret 路径定义，因为 KV v2 的路径通常会有所不同:

```
vault.hashicorp.com/secret-volume-path-{{ $config.outputFile }}: {{ $config.volumePath }}
vault.hashicorp.com/agent-inject-secret-{{ $config.outputFile }}: {{ if eq (int $.Values.vault.version) 2 }}secret/data/{{ end }}kv/{{ $.Values.teamId }}/{{ default $.Values.namespacePrefix $config.secretPath }}
```

这样的修改可以让你的配置同时支持 KV v1 和 v2 引擎。记住在使用时需要正确设置 `.Values.vault.version` 的值(1 或 2)。

人工智能的时代来临啦-做增长运营的小曦记录

**Comment by zking2000** [comment]
``` 

{{- define "vault.secrets.secretConfig" -}}
  {{- range $index, $config := .Values.vault.secretConfig -}}
    {{- if $config.autoOutputFile -}}
      vault.hashicorp.com/secret-volume-path="{{ $config.outputFile }}" {{ $config.volumePath }} {{ $.Values.namespacePrefix }}{{ $config.secretPath }}
    {{- else -}}
      {{- $pathPrefix := "kv" -}}
      {{- if eq (int $.Values.vault.version) 2 -}}
        {{- $pathPrefix = "kv_v2" -}}
      {{- end -}}
      {{- $secretPath := printf "secret/data/%s/%s/%s" $pathPrefix $.Values.teamId $config.secretPath -}}
      vault.hashicorp.com/agent-inject-template-{{ $config.outputFile }}="{{
        printf \"{{- with secret \\\"%s\\\" -}}\\n{{ toYaml .Data.data | nindent 2 }}\\n{{- end -}}\" $secretPath }}"
    {{- end -}}
  {{- end -}}
{{- end -}}

```

**Comment by zking2000** [comment]
``` 

{{- define "vault.secrets" -}}
{{- range $key, $value := .config.secrets }}
  {{- if eq (int $.Values.vault.version) 1 }}
    {{ $key }}: {{ "{{ \" " }}index .Data.data "{{ $value }}" | trim {{ " \" }}" }}
  {{- else if eq (int $.Values.vault.version) 2 }}
    {{ $key }}: {{ "{{ \" " }}index .Data.data "{{ $value }}" | trim {{ " \" }}" }}
  {{- else }}
    {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." -}}
  {{- end }}
{{- end }}
{{- end }}

```

**Comment by zking2000** [comment]
``` 

vault.hashicorp.com/log-level: {{ .Values.vault.logLevel | quote }}
vault.hashicorp.com/auth-path: {{ printf "auth/kubernetes/%s" .Values.teamId | quote }}
vault.hashicorp.com/namespace: {{ .Values.vault.namespace | quote }}
vault.hashicorp.com/role: {{ default .Values.namespacePrefix .Values.vault.role | quote }}
vault.hashicorp.com/service: {{ .Values.vault.vaultAddr | quote }}

{{- include "vault.secrets.secretConfig" . }}

{{- define "vault.secrets.secretConfig" }}
{{- range $index, $config := .Values.vault.secretConfig }}
  {{- if $config.outPutFile }}
    vault.hashicorp.com/secret-volume-path-{{ $index }}: {{ $config.outPutFile }}
  {{- end }}
  vault.hashicorp.com/agent-inject-secret-{{ $index }}: {{ if eq (int $.Values.vault.version) 2 }}secrets/kv_v2/{{ $config.secretPath }}{{ else }}{{ $config.secretPath }}{{ end }}
  vault.hashicorp.com/agent-inject-template-{{ $index }}: |
    {{- printf "config \"%s\" {\n  path = \"%s\"\n}" $.Values.vault.version (if eq (int $.Values.vault.version) 2 "kv_v2" "kv") }}
    {{- if $config.secretPath }}
      path_prefix = "{{ $.Values.namespacePrefix }}/{{ $config.secretPath }}"
    {{- end }}
{{- end }}
{{- end }}

{{- define "vault.secrets" }}
{{- range $key, $value := .config.secrets }}
  {{- if eq (int $.Values.vault.version) 1 }}
    {{ $key }}: {{ "{{ index .Data.data \"${value}\" | trim }}" }}
  {{- else if eq (int $.Values.vault.version) 2 }}
    {{ $key }}: {{ "{{ index .Data.data \"${value}\" | trim }}" }}
  {{- else }}
    {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." }}
  {{- end }}
{{- end }}
{{- end }}

```

**Comment by zking2000** [comment]
``` 

vault.hashicorp.com/role: {{ default .Values.namespacePrefix .Values.vault.role | quote }}
vault.hashicorp.com/service: {{ .Values.vault.vaultAddr | quote }}

{{- include "vault.secrets.secretConfig" . }}

{{- define "vault.secrets.secretConfig" -}}
{{- range $index, $config := .Values.vault.secretConfig }}
  {{- if $config.outPutFile }}
    vault.hashicorp.com/secret-volume-path-{{ $index }}: {{ $config.outPutFile }}
  {{- end }}
  vault.hashicorp.com/agent-inject-secret-{{ $index }}: {{ if eq (int $.Values.vault.version) 2 }}secrets/kv_v2/{{ $config.secretPath }}{{ else }}{{ $config.secretPath }}{{ end }}
  vault.hashicorp.com/agent-inject-template-{{ $index }}: |
    {{- printf "config \"%s\" {\n  path = \"%s\"\n}" $.Values.vault.version (if eq (int $.Values.vault.version) 2 "kv_v2" "kv") }}
    {{- if $config.secretPath }}
      path_prefix = "{{ $.Values.namespacePrefix }}/{{ $config.secretPath }}"
    {{- end }}
{{- end }}
{{- end }}

{{- define "vault.secrets" -}}
{{- range $key, $value := .config.secrets }}
  {{- if eq (int $.Values.vault.version) 1 }}
    {{ $key }}: {{ "{{ index .Data.data \"${value}\" | trim }}" }}
  {{- else if eq (int $.Values.vault.version) 2 }}
    {{ $key }}: {{ "{{ index .Data.data \"${value}\" | trim }}" }}
  {{- else }}
    {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." }}
  {{- end }}
{{- end }}
{{- end }}

```

**Comment by zking2000** [comment]
``` 

vault.hashicorp.com/role: {{ default .Values.namespacePrefix .Values.vault.role | quote }}
vault.hashicorp.com/service: {{ .Values.vault.vaultAddr | quote }}

{{- include "vault.secrets.secretConfig" . }}

{{- define "vault.secrets.secretConfig" -}}
{{- range $index, $config := .Values.vault.secretConfig }}
  {{- if $config.outPutFile }}
    vault.hashicorp.com/secret-volume-path-{{ $index }}: {{ $config.outPutFile }}
  {{- end }}
  vault.hashicorp.com/agent-inject-secret-{{ $index }}: {{ if eq (int $.Values.vault.version) 2 }}secrets/kv_v2/{{ $config.secretPath }}{{ else }}{{ $config.secretPath }}{{ end }}
  vault.hashicorp.com/agent-inject-template-{{ $index }}: |
    {{- $data := dict "config" $config "version" $.Values.vault.version }}
    {{- $pathPrefix := "kv" }}
    {{- if eq (int $.Values.vault.version) 2 }}{{ $pathPrefix = "kv_v2" }}{{- end }}
    {{- $secretPath := (print "secrets/" $pathPrefix "/" $.Values.teamId "/" (default $.Values.namespacePrefix $config.secretPath)) }}
    {{ with secret $secretPath }}
      {{- include "vault.secrets" $data | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}

{{- define "vault.secrets" -}}
{{- range $key, $value := .config.secrets }}
  {{- if eq (int $.Values.vault.version) 1 }}
    {{ $key }}: {{ index .Data.data $value | trim }}
  {{- else if eq (int $.Values.vault.version) 2 }}
    {{ $key }}: {{ index .Data.data $value | trim }}
  {{- else }}
    {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." }}
  {{- end }}
{{- end }}
{{- end }}

```

**Comment by zking2000** [comment]
这段代码看起来是一个模板文件，用于处理 HashiCorp Vault 相关的配置和密钥管理。我将格式化输出这段代码：

```hcl
{{- include "vault.secrets.secretConfig" . }}
{{- end -}}

{{- define "vault.secrets.secretConfig" -}}
{{- range $index, $config := .Values.vault.secretConfig }}
{{- if $config.outputFile }}
vault.hashicorp.com/secret-volume-path-{{ $config.outputFile }}: {{ $config.volumePath }}
vault.hashicorp.com/agent-inject-secret-{{ $config.outputFile }}: {{ if eq (int $.Values.vault.version) 2 }}secrets/kv_v2/{{ else }}kv/{{ end }}{{ $.Values.teamId }}/{{ default $.Values.namespacePrefix $config.secretPath }}
vault.hashicorp.com/agent-inject-template-{{ $config.outputFile }}: |
    {{- $data := dict "config" $config "version" $.Values.vault.version }}
    {{- $pathPrefix := "kv" }}
    {{- if eq (int $.Values.vault.version) 2 }}{{- $pathPrefix = "kv_v2" }}{{- end }}
    {{- $secretPath := (printf "secrets/%s/%s/%s" $pathPrefix $.Values.teamId (default $.Values.namespacePrefix $config.secretPath)) }}
    {{- printf "{{- with secret \"%s\" }}" $secretPath | nindent 4 }}
{{- include "vault.secrets" $data | nindent 4 }}
    {{- printf "{{- end }}" | nindent 4 }}
    {{- end }}
{{- end -}}
{{- end -}}

{{- define "vault.secrets" -}}
{{- range $key, $value := .config.secrets }}
    {{- if eq (int $.version) 1 }}
        {{- printf "%s: {{- index .Data \"%s\" | trim }}" $key $value }}
    {{- else if eq (int $.version) 2 }}
        {{- printf "%s: {{- index .Data.data \"%s\" | trim }}" $key $value }}
    {{- else }}
        {{- fail "Unsupported KV engine version. Only version 1 and 2 are supported." }}
    {{- end }}
{{- end }}
{{- end -}}
```

这段代码的主要功能是：

1. 定义了多个模板函数用于处理 Vault 密钥配置
2. 支持 Vault KV 引擎的版本 1 和版本 2
3. 生成 Vault agent 注入所需的注解配置
4. 处理密钥路径和模板渲染

代码的主要组成部分：
- `vault.secrets.secretConfig` 模板：处理主要的密钥配置和路径生成
- `vault.secrets` 模板：根据不同的 KV 引擎版本格式化密钥输出
- 包含了条件判断来处理不同版本的 KV 引擎
- 使用了嵌套模板和缩进控制来生成格式化的输出

这似乎是一个用于 Kubernetes 的 Helm Chart 模板，用于配置 Vault Agent Injector 的行为。​​​​​​​​​​​​​​​​

**Comment by zking2000** [comment]
从渲染后的模板内容来看，我注意到几个可能导致错误的地方：

1. 模板格式问题：
```yaml
vault.hashicorp.com/agent-inject-template-esg-db-dev.yml: >
  {{- with secret "secrets/kv_v2/wsit/wsit-gdt-esg-sa-writeback" }}
```
这里的模板语法和缩进可能有问题，建议修改为：
```yaml
vault.hashicorp.com/agent-inject-template-esg-db-dev.yml: |
    {{- with secret "secrets/kv_v2/wsit/wsit-gdt-esg-sa-writeback" }}
      spring.datasource.password: {{ index .Data.data "db_dev_password" | trim }}
      spring.datasource.username: {{ index .Data.data "db_dev_username" | trim }}
    {{- end }}
```

2. 资源限制设置的问题：
```yaml
vault.hashicorp.com/agent-limits-cpu: 50m
vault.hashicorp.com/agent-limits-mem: 68Mi
```
建议确保这些资源限制足够运行您的应用。如果出现OOM或CPU限制相关错误，可以适当调整这些值。

3. 路径和权限问题：
```yaml
vault.hashicorp.com/auth-path: auth/kubernetes/wsit_uk-azr-301
```
请确认：
- Vault的认证路径是否正确
- ServiceAccount是否有正确的权限
- 对应的Kubernetes Auth方法是否在Vault中正确配置

4. Vault KV版本问题：
确保您的路径 `secrets/kv_v2/wsit/wsit-gdt-esg-sa-writeback` 确实是一个有效的KV v2路径，且包含了所需的密钥。

5. 建议添加的配置：
```yaml
vault.hashicorp.com/agent-run-as-user: "100"
vault.hashicorp.com/agent-run-as-group: "1000"
vault.hashicorp.com/tls-skip-verify: "true"  # 仅在开发环境使用
```

6. 完整的修改建议：
```yaml
sidecar.istio.io/proxyMemory: 300Mi
sidecar.istio.io/proxyMemoryLimit: 500Mi
sidecar.istio.io/rewriteAppHTTPProbers: 'false'
vault.hashicorp.com/agent-init-first: 'true'
vault.hashicorp.com/agent-inject: 'true'
vault.hashicorp.com/agent-inject-secret-esg-db-dev.yml: secrets/kv_v2/wsit/wsit-gdt-esg-sa-writeback
vault.hashicorp.com/agent-inject-template-esg-db-dev.yml: |
    {{- with secret "secrets/kv_v2/wsit/wsit-gdt-esg-sa-writeback" }}
      spring.datasource.password: {{ index .Data.data "db_dev_password" | trim }}
      spring.datasource.username: {{ index .Data.data "db_dev_username" | trim }}
    {{- end }}
vault.hashicorp.com/agent-limits-cpu: 100m       # 增加CPU限制
vault.hashicorp.com/agent-limits-mem: 128Mi      # 增加内存限制
vault.hashicorp.com/agent-pre-populate-only: 'true'
vault.hashicorp.com/agent-requests-cpu: 50m
vault.hashicorp.com/agent-requests-mem: 64Mi
vault.hashicorp.com/auth-path: auth/kubernetes/wsit_uk-azr-301
vault.hashicorp.com/ca-cert: /vault/tls/ca.pem
vault.hashicorp.com/log-level: info
```

7. 检查事项：
- 确认 Vault 服务器是否可访问
- 检查 ServiceAccount 权限
- 验证密钥路径和值是否存在
- 检查 Vault Token 的权限
- 查看 Pod 的事件和日志以获取具体错误信息

如果还遇到问题，建议：
1. 使用 `kubectl describe pod <pod-name>` 查看具体的错误信息
2. 检查 Vault Agent 的日志输出
3. 临时将日志级别调整为 debug：`vault.hashicorp.com/log-level: debug`​​​​​​​​​​​​​​​​

**Comment by zking2000** [comment]
我来帮你修改 Helm 模板代码，以生成正确的 Vault 配置。基于之前的错误，主要需要修改 template 部分的格式和路径处理：

```hcl
{{- define "vault.secrets.secretConfig" -}}
{{- range $index, $config := .Values.vault.secretConfig }}
{{- if $config.outputFile }}
# 设置 volume 路径
vault.hashicorp.com/secret-volume-path-{{ $config.outputFile }}: {{ $config.volumePath }}

# 设置要注入的 secret 路径
vault.hashicorp.com/agent-inject-secret-{{ $config.outputFile }}: {{ if eq (int $.Values.vault.version) 2 }}secrets/kv_v2/{{ else }}kv/{{ end }}{{ $.Values.teamId }}/{{ default $.Values.namespacePrefix $config.secretPath }}

# 设置 secret 模板
vault.hashicorp.com/agent-inject-template-{{ $config.outputFile }}: |
    {{- $secretPath := printf "secrets/%s/%s/%s" (eq (int $.Values.vault.version) 2 | ternary "kv_v2" "kv") $.Values.teamId (default $.Values.namespacePrefix $config.secretPath) }}
    {{- printf "{{- with secret \"%s\" }}" $secretPath | nindent 4 }}
    {{- range $key, $value := $config.secrets }}
        {{- if eq (int $.Values.vault.version) 1 }}
    {{ $key }}: {{ printf "{{- index .Data \"%s\" | trim }}" $value | nindent 4 }}
        {{- else }}
    {{ $key }}: {{ printf "{{- index .Data.data \"%s\" | trim }}" $value | nindent 4 }}
        {{- end }}
    {{- end }}
    {{- printf "{{- end }}" | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
```

你的 values.yaml 可以这样配置：

```yaml
vault:
  version: 2  # KV 引擎版本
  teamId: "wsit"
  namespacePrefix: "default"
  secretConfig:
    - outputFile: "esg-db-dev.yml"
      volumePath: "/vault/secrets"
      secretPath: "wsit-gdt-esg-sa-writeback"
      secrets:
        spring.datasource.password: "db_dev_password"
        spring.datasource.username: "db_dev_username"
```

主要改进点：

1. 模板格式处理：
   - 使用 `|` 来保持多行字符串格式
   - 正确处理缩进使用 `nindent`
   - 确保生成的模板语法正确

2. 路径处理：
   - 统一路径生成逻辑
   - 正确处理 KV v1/v2 的路径差异

3. 数据访问：
   - 根据 KV 版本正确访问数据结构
   - V1: `.Data.key`
   - V2: `.Data.data.key`

4. 完整配置示例：

```yaml
# deployment.yaml 或其他 Kubernetes 资源文件
metadata:
  annotations:
    sidecar.istio.io/proxyMemory: 300Mi
    sidecar.istio.io/proxyMemoryLimit: 500Mi
    vault.hashicorp.com/agent-init-first: 'true'
    vault.hashicorp.com/agent-inject: 'true'
    vault.hashicorp.com/agent-limits-cpu: '100m'
    vault.hashicorp.com/agent-limits-mem: '128Mi'
    vault.hashicorp.com/agent-requests-cpu: '50m'
    vault.hashicorp.com/agent-requests-mem: '64Mi'
    vault.hashicorp.com/auth-path: "auth/kubernetes/wsit_uk-azr-301"
    vault.hashicorp.com/ca-cert: "/vault/tls/ca.pem"
    vault.hashicorp.com/log-level: "info"
    {{- include "vault.secrets.secretConfig" . | nindent 4 }}
```

使用时注意：

1. 确保 values.yaml 中的配置正确：
   - `vault.version` 要匹配实际的 KV 引擎版本
   - `teamId` 和 `secretPath` 要匹配实际的密钥路径
   - `secrets` 映射要正确匹配 Vault 中的键名

2. 验证生成的模板：
   ```bash
   helm template . -f values.yaml
   ```

3. 如果还有问题，可以通过设置 debug 日志级别来排查：
   ```yaml
   vault.hashicorp.com/log-level: "debug"
   ```

这样修改后，应该能生成正确的 Vault 模板并且可以被正确解析执行。如果还有具体的错误信息，请提供出来我们可以进一步调整。​​​​​​​​​​​​​​​​
