### ISSUE TITLE
GKE Internal Ingress - GCE Ingress

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#20]
#### Create GKE Cluster
```
provider "google" {
  credentials = file("./sa.json")
  project     = "${var.project}"
  region      = "${var.region}"
}

resource "google_container_cluster" "private_cluster" {
  provider = google-beta
  project = "${var.project}"

  name     = "private-cluster"
  location = "${var.region}"

  deletion_protection = false

  network = google_compute_network.vpc_network.self_link
  subnetwork = google_compute_subnetwork.subnet.self_link

  private_cluster_config {
    enable_private_nodes   = true
    enable_private_endpoint = true
    master_ipv4_cidr_block = "172.16.0.0/28"
  }

  master_authorized_networks_config {
    cidr_blocks {
      cidr_block   = "192.168.64.0/24"
      display_name = "any"
    }
  }

  ip_allocation_policy {}

  remove_default_node_pool = true
  initial_node_count       = 1

  # Enable Managed Prometheus
  # monitoring_service = "monitoring.googleapis.com/kubernetes"

  workload_identity_config {
    workload_pool = "${var.project}.svc.id.goog"
  }

  monitoring_config {
    enable_components = [ "SYSTEM_COMPONENTS", "APISERVER", "CONTROLLER_MANAGER", "SCHEDULER" ]

    managed_prometheus {
      enabled = true
    }
  }
}

resource "google_container_node_pool" "private_cluster_node_pool" {
  provider = google-beta
  project = "${var.project}"

  name     = "private-cluster-node-pool"
  location = "${var.region}"
  cluster  = google_container_cluster.private_cluster.name

  initial_node_count = 1
  node_locations     = ["${var.region}-b"]

  node_config {
    machine_type = "e2-medium"
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]

    metadata = {
      disable-legacy-endpoints = "true"
    }

    tags = ["no-external-ip"]
    preemptible  = true
  }

  management {
    auto_repair = true
  }
}

resource "google_compute_network" "vpc_network" {
  name = "gke-network"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnet" {
  name          = "subnet"
  ip_cidr_range = "192.168.64.0/24"
  region        = "${var.region}"
  network       = google_compute_network.vpc_network.self_link
}

resource "google_compute_instance" "squid_proxy" {
  name         = "squid-proxy"
  machine_type = "n1-standard-1"
  zone         = "${var.region}-a"

  boot_disk {
    initialize_params {
      image = "ubuntu-os-cloud/ubuntu-2004-lts"
    }
  }

  network_interface {
    network    = google_compute_network.vpc_network.name
    subnetwork = google_compute_subnetwork.subnet.name

    access_config {
    }
  }

  metadata_startup_script = <<-EOT
    #! /bin/bash
    sudo apt-get update
    sudo apt-get install -y squid
    sudo sed -i 's/http_access deny all/http_access allow all/' /etc/squid/squid.conf
    sudo systemctl restart squid
  EOT

  service_account {
    scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
  }

  tags = ["squid-proxy"]
}

resource "google_compute_firewall" "no_external_ip_firewall" {
  name    = "no-external-ip-firewall"
  network = google_compute_network.vpc_network.self_link
  priority = 65535

  source_ranges = ["0.0.0.0/0"]

  target_tags = ["no-external-ip"]

  deny {
    protocol = "icmp"
  }

  deny {
    protocol = "tcp"
  }

  deny {
    protocol = "udp"
  }
}

resource "google_compute_firewall" "allow_ports_firewall" {
  name    = "allow-squid"
  network = google_compute_network.vpc_network.name

  allow {
    protocol = "tcp"
    ports    = ["3128"]
  }

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["0.0.0.0/0"]
  target_tags = ["squid-proxy"]

  description = "Allow traffic on port 3128 for Squid proxy from the GKE cluster subnet"
}

resource "google_compute_firewall" "allow_proxy_to_pod" {
  name    = "allow-proxy-to-pod"
  network = google_compute_network.vpc_network.name

  allow {
    protocol = "tcp"
    ports    = ["8080"]
  }

  allow {
    protocol = "tcp"
    ports    = ["80"]
  }

  source_ranges = ["192.168.1.0/24"]

  description = "Allow traffic from proxy subnet to GKE Pods on port 8080"
}

variable "project" {
  default = "causal-hour-418204"
  type = string
}

variable "region" {
  default = "asia-east1"
  type = string
}
```
#### Prepare Kubernetes Resources
```
# default.conf

# HTTPS server
server {
    listen       443 ssl;
    server_name  nginx.stephende.top;

    ssl_certificate     /opt/nginx/ssl/fullchain.pem;
    ssl_certificate_key /opt/nginx/ssl/private.key;

    location /health {
        root   /usr/share/nginx/html;
        try_files /index.html =404;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


# fullchain.pem & privkey.pem
```
#### Apply Kubernetes Resources as below
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: ssl-secret
          mountPath: /opt/nginx/ssl/
      volumes:
      - name: config-volume
        configMap:
          name: ssl-config
      - name: ssl-secret
        secret:
          secretName: secret-ssl
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: hc-gce-ingress
  namespace: default
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTPS
    requestPath: /health
    port: 443
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "hc-gce-ingress"}'
    cloud.google.com/app-protocols: '{"nginx": "HTTPS"}'
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
---
# if got 400 bad request issue when get call gce ingress

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress
  annotations:
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.regional-static-ip-name: gce-ingress-ssl
    kubernetes.io/ingress.allow-http: "false"
    ingress.gcp.kubernetes.io/backend-config: '{"default":"hc-gce-ingress"}'
  namespace: default
spec:
  ingressClassName: gce-internal
  rules:
  - host: nginx.stephende.top
    http:
      paths:
      - backend:
          service:
            name: nginx
            port:
              number: 443
        path: /health
        pathType: Prefix
  tls:
  - hosts:
    - nginx.stephende.top
    secretName: secret-ingress
---
```

#### Script to deploy Kubernetes Resources
```
SQUID_IP=$(gcloud compute instances list --format="csv[no-heading](name,networkInterfaces[].accessConfigs[0].natIP)" | awk -F, '$2 != "" && $2 != "None" {print $2}')

echo "SQUID_IP: $SQUID_IP"

export https_proxy=http://$SQUID_IP:3128

kubectl create cm ssl-config --from-file=default.conf

kubectl create secret generic secret-ssl --from-file=fullchain.pem=./ohttps/fullchain.pem --from-file=private.key=./ohttps/privkey.pem

kubectl create secret tls secret-ingress --cert=./ohttps/fullchain.pem --key=./ohttps/privkey.pem

kubectl apply -f deployment.yaml

kubectl expose deploy nginx --target-port 443 --port 443

kubectl apply -f backendconfig.yaml

kubectl apply -f ingress.yaml
```
