### ISSUE TITLE
Affinity

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#24]
要将Pod平均分布在不同的GCP区域中的不同工作节点上，你可以使用Kubernetes的`PodAntiAffinity`特性来实现。这个特性可以确保Pod不会被调度到同一个节点或同一个区域。以下是一个示例的部署清单：

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - my-app
              topologyKey: "kubernetes.io/hostname"
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - my-app
              topologyKey: "topology.kubernetes.io/zone"
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
```

### 解释

1. **Deployment**:
    - 定义了一个名为`my-app`的Deployment，它将创建三个副本（Pods）。

2. **Affinity**:
    - 在`spec`部分，我们定义了`affinity`规则。
    - `podAntiAffinity`确保Pod不会调度到同一个节点和同一个区域。

3. **TopologyKey**:
    - `topologyKey: "kubernetes.io/hostname"`：确保同一个节点上不会调度多个相同标签的Pod。
    - `topologyKey: "topology.kubernetes.io/zone"`：确保同一个区域内不会调度多个相同标签的Pod。

4. **Containers**:
    - 定义了容器的镜像和端口。

通过这种方式，Kubernetes调度器会确保你的Pods平均分布在不同的GCP区域和节点上。

如果你需要进一步的定制或其他特性，请告诉我。
