### ISSUE TITLE
Deny exec permission

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#29]
```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: no-exec-role
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: []

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: no-exec-binding
  namespace: default
subjects:
- kind: User
  name: "example-user"
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: no-exec-role
  apiGroup: rbac.authorization.k8s.io

kubectl auth can-i exec pod-name --as=example-user
```

```mermaid
graph LR
  User -- Request --> K8s_API[Kubernetes API Server]
  K8s_API -- Authorization --> RoleBinding[RoleBinding]
  RoleBinding -- Binds --> Role[Role: no-exec-role]
  Role -- Restricts --> K8s_API
  K8s_API -- Response --> User
```

**Comment by zking2000** [comment]
Using OPA - Gatekeeper

kubectl apply -f https://raw.githubusercontent.com/jcanizalez/gatekeeper/master/deploy/gatekeeper.yaml


```
apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdenyexec
spec:
  crd:
    spec:
      names:
        kind: k8sdenyexec
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenyexec
        import future.keywords.every
        violation[{"msg": msg}] {
          input.review.object.stdin == true
          msg :=  "Interactive exec is not permitted."
        }
        allowed_commands := {"ls","cat"}
        violation[{"msg": msg}] {
          some command in input.review.object.command
            not command in allowed_commands
          msg := sprintf("Only %v commands are allowed.", [allowed_commands])
        }
```

```
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: k8sdenyexec
metadata:
  name: k8sdenyexec
spec:
  match:
    kinds:
      - apiGroups: [ "" ]
        kinds: [ "PodExecOptions" ]
```
