### ISSUE TITLE
kind

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#42]
```
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080
        protocol: TCP
    extraMounts:
      - hostPath: /path/to/your/config
        containerPath: /container/mount/path
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-ip: "0.0.0.0"
    extraEnvs:
      - name: HTTP_PROXY
        value: "http://your.proxy.server:port"
      - name: HTTPS_PROXY
        value: "http://your.proxy.server:port"
      - name: NO_PROXY
        value: "localhost,127.0.0.1,.yourdomain.com"

```
