### ISSUE TITLE
jenkins

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#54]
```
---
apiVersion: v1
kind: Secret
metadata:
  name: external-jenkins-secret
type: Opaque
stringData:
  JENKINS_URL: https://your-external-jenkins-url:port
  JENKINS_USER: your_jenkins_username
  JENKINS_API_TOKEN: your_jenkins_api_token
```

```
from airflow import DAG
from airflow.providers.cncf.kubernetes.operators.kubernetes_pod import KubernetesPodOperator
from airflow.utils.dates import days_ago

default_args = {
    'owner': 'airflow',
    'start_date': days_ago(1),
}

dag = DAG(
    'trigger_external_jenkins_job',
    default_args=default_args,
    schedule_interval=None,
    catchup=False,
)

trigger_jenkins = KubernetesPodOperator(
    task_id="trigger_external_jenkins_job",
    name="trigger-external-jenkins-job",
    namespace="default",
    image="python:3.8-slim",
    cmds=["sh", "-c"],
    arguments=["""
    pip install python-jenkins &&
    python -c "
import os
import jenkins

jenkins_url = os.environ['JENKINS_URL']
jenkins_user = os.environ['JENKINS_USER']
jenkins_token = os.environ['JENKINS_API_TOKEN']

server = jenkins.Jenkins(jenkins_url, username=jenkins_user, password=jenkins_token)
job_name = 'your_jenkins_job_name'
server.build_job(job_name)
print(f'External Jenkins job {job_name} triggered successfully')
    "
    """],
    env_from=[
        {'secret_ref': {'name': 'external-jenkins-secret'}}
    ],
    is_delete_operator_pod=True,
    in_cluster=True,
    dag=dag,
)

trigger_jenkins
```
