### ISSUE TITLE
otelcol

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#67]
```
tar xzf otelcol-contrib_0.89.0_linux_amd64.tar.gz


sudo mv otelcol-contrib /usr/local/bin/otelcol


sudo mkdir -p /etc/otel
sudo nano /etc/otel/config.yaml

```

```
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging]
```

```
sudo nano /etc/systemd/system/otel-agent.service

```

```
[Unit]
Description=OpenTelemetry Collector Agent
After=network.target

[Service]
ExecStart=/usr/local/bin/otelcol --config /etc/otel/config.yaml
Restart=always
User=otel
Group=otel

[Install]
WantedBy=multi-user.target
```

```
sudo useradd -rs /bin/false otel


sudo chown -R otel:otel /etc/otel
sudo chmod 755 /usr/local/bin/otelcol


sudo systemctl daemon-reload
sudo systemctl start otel-agent
sudo systemctl enable otel-agent


sudo systemctl status otel-agent


sudo journalctl -u otel-agent
```

**Comment by zking2000** [comment]
```
service:
  telemetry:
    logs:
      level: "info"
      development: false
      encoding: "json"
      outputPaths: ["/var/log/otel-agent.log", "stdout"]
      errorOutputPaths: ["/var/log/otel-agent-error.log", "stderr"]
```
