### ISSUE TITLE
webhook2

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#79]
```
#!/bin/bash

set -e

SERVICE=$1
NAMESPACE=$2
SECRET=$3
WEBHOOK_NAME=$4

TMPDIR=$(mktemp -d)
echo "creating certs in tmpdir ${TMPDIR}"

cat <<EOF >> ${TMPDIR}/csr.conf
[ req ]
default_bits       = 2048
prompt             = no
default_md         = sha256
req_extensions     = req_ext
distinguished_name = dn

[ dn ]
CN = ${WEBHOOK_NAME}

[ req_ext ]
subjectAltName = @alt_names

[ alt_names ]
DNS.1 = ${WEBHOOK_NAME}
DNS.2 = ${SERVICE}
DNS.3 = ${SERVICE}.${NAMESPACE}
DNS.4 = ${SERVICE}.${NAMESPACE}.svc
EOF

openssl genrsa -out ${TMPDIR}/ca.key 2048
openssl req -x509 -new -nodes -key ${TMPDIR}/ca.key -subj "/CN=${WEBHOOK_NAME}" -days 10000 -out ${TMPDIR}/ca.crt
openssl genrsa -out ${TMPDIR}/server.key 2048
openssl req -new -key ${TMPDIR}/server.key -out ${TMPDIR}/server.csr -config ${TMPDIR}/csr.conf
openssl x509 -req -in ${TMPDIR}/server.csr -CA ${TMPDIR}/ca.crt -CAkey ${TMPDIR}/ca.key -CAcreateserial -out ${TMPDIR}/server.crt -days 10000 -extensions req_ext -extfile ${TMPDIR}/csr.conf

kubectl create secret tls ${SECRET} \
        --cert=${TMPDIR}/server.crt \
        --key=${TMPDIR}/server.key \
        --namespace=${NAMESPACE}

echo "Secret ${SECRET} created in namespace ${NAMESPACE}"
```

```
apiVersion: v1
kind: Namespace
metadata:
  name: admission-control

---
apiVersion: v1
kind: Service
metadata:
  name: otel-sidecar-injector
  namespace: admission-control
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: otel-sidecar-injector

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-sidecar-injector
  namespace: admission-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-sidecar-injector
  template:
    metadata:
      labels:
        app: otel-sidecar-injector
    spec:
      containers:
      - name: webhook
        image: otel-sidecar-injector:latest
        ports:
        - containerPort: 443
        volumeMounts:
        - name: webhook-certs
          mountPath: "/tls"
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: otel-sidecar-injector

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: otel-sidecar-injector
webhooks:
  - name: otel-sidecar-injector.admission-control.svc.cluster.local
    clientConfig:
      service:
        name: otel-sidecar-injector
        namespace: admission-control
        path: "/mutate-pods"
      caBundle: <CA_BUNDLE>
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1"]
    sideEffects: None
```

```
from kubernetes import client, config
from flask import Flask, request, jsonify
import os
import base64

app = Flask(__name__)

# 加载Kubernetes配置
config.load_incluster_config()

def namespace_has_label(namespace_name, label_key, label_value):
    v1 = client.CoreV1Api()
    try:
        namespace = v1.read_namespace(name=namespace_name)
        labels = namespace.metadata.labels
        return labels.get(label_key) == label_value
    except client.rest.ApiException as e:
        print(f"API异常: {e}")
        return False

@app.route("/mutate-pods", methods=["POST"])
def handle_admission_review():
    request_json = request.get_json()
    admission_review = client.V1AdmissionReview(**request_json)

    namespace = admission_review.request.namespace
    if namespace_has_label(namespace, "auto-injection", "enabled"):
        otel_container = client.V1Container(
            name="otel-collector",
            image="otel/opentelemetry-collector:latest",
            ports=[client.V1ContainerPort(container_port=4317)]
        )
        patch = [{
            "op": "add",
            "path": "/spec/containers/-",
            "value": otel_container
        }]
        patch_response = client.V1AdmissionResponse(
            uid=admission_review.request.uid,
            allowed=True,
            patch_type="JSONPatch",
            patch=base64.b64encode(client.V1Patch(patch).serialize()).decode()
        )
    else:
        patch_response = client.V1AdmissionResponse(
            uid=admission_review.request.uid,
            allowed=True
        )

    admission_review_response = client.V1AdmissionReview(
        response=patch_response
    )
    return jsonify(admission_review_response.to_dict())

if __name__ == "__main__":
    app.run(host='0.0.0.0', port=443, ssl_context=('/tls/tls.crt', '/tls/tls.key'))
```
