### ISSUE TITLE
metrics

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#83]
```
from prometheus_client import start_http_server, Gauge, Counter
import psutil
import time
import threading
from kubernetes import client, config

# 系统资源指标
cpu_usage = Gauge('cpu_usage_percent', 'CPU usage in percent')
memory_usage = Gauge('memory_usage_percent', 'Memory usage in percent')
disk_usage = Gauge('disk_usage_percent', 'Disk usage in percent')
network_io_sent = Counter('network_io_bytes_sent', 'Network IO bytes sent')
network_io_recv = Counter('network_io_bytes_recv', 'Network IO bytes received')

# Kubernetes metrics
config.load_incluster_config()
v1 = client.CoreV1Api()

# Pod 和容器指标
pod_cpu_usage = Gauge('pod_cpu_usage', 'Pod CPU usage in cores', ['namespace', 'pod'])
pod_memory_usage = Gauge('pod_memory_usage', 'Pod memory usage in bytes', ['namespace', 'pod'])
container_cpu_usage = Gauge('container_cpu_usage', 'Container CPU usage in cores', ['namespace', 'pod', 'container'])
container_memory_usage = Gauge('container_memory_usage', 'Container memory usage in bytes', ['namespace', 'pod', 'container'])
container_restarts = Counter('container_restarts', 'Container restart count', ['namespace', 'pod', 'container'])
container_ready = Gauge('container_ready', 'Container ready status', ['namespace', 'pod', 'container'])
container_status = Gauge('container_status', 'Container status', ['namespace', 'pod', 'container', 'status'])

def collect_system_metrics():
    while True:
        cpu_usage.set(psutil.cpu_percent())
        memory = psutil.virtual_memory()
        memory_usage.set(memory.percent)
        disk = psutil.disk_usage('/')
        disk_usage.set(disk.percent)
        net_io = psutil.net_io_counters()
        network_io_sent.inc(net_io.bytes_sent)
        network_io_recv.inc(net_io.bytes_recv)
        time.sleep(5)  # 每5秒更新一次

def collect_k8s_metrics():
    while True:
        pods = v1.list_pod_for_all_namespaces(watch=False)
        for pod in pods.items:
            namespace = pod.metadata.namespace
            pod_name = pod.metadata.name

            # 获取 Pod 的资源使用情况
            try:
                pod_metrics = v1.read_namespaced_pod_status(name=pod_name, namespace=namespace)
                if pod_metrics.status and pod_metrics.status.container_statuses:
                    total_cpu_usage = 0
                    total_memory_usage = 0
                    for container_status in pod_metrics.status.container_statuses:
                        container_name = container_status.name
                        
                        # 容器 CPU 使用
                        if container_status.usage and container_status.usage.cpu:
                            cpu_usage_cores = int(container_status.usage.cpu) / 1e9  # 转换为核心数
                            container_cpu_usage.labels(namespace=namespace, pod=pod_name, container=container_name).set(cpu_usage_cores)
                            total_cpu_usage += cpu_usage_cores

                        # 容器内存使用
                        if container_status.usage and container_status.usage.memory:
                            memory_usage_bytes = int(container_status.usage.memory)
                            container_memory_usage.labels(namespace=namespace, pod=pod_name, container=container_name).set(memory_usage_bytes)
                            total_memory_usage += memory_usage_bytes

                        # 容器重启次数
                        container_restarts.labels(namespace=namespace, pod=pod_name, container=container_name).inc(container_status.restart_count)

                        # 容器就绪状态
                        container_ready.labels(namespace=namespace, pod=pod_name, container=container_name).set(1 if container_status.ready else 0)

                        # 容器状态
                        for status_type, status_info in container_status.state.to_dict().items():
                            if status_info is not None:
                                container_status.labels(namespace=namespace, pod=pod_name, container=container_name, status=status_type).set(1)
                            else:
                                container_status.labels(namespace=namespace, pod=pod_name, container=container_name, status=status_type).set(0)

                    # 设置 Pod 总体资源使用
                    pod_cpu_usage.labels(namespace=namespace, pod=pod_name).set(total_cpu_usage)
                    pod_memory_usage.labels(namespace=namespace, pod=pod_name).set(total_memory_usage)

            except client.exceptions.ApiException as e:
                print(f"Error fetching metrics for pod {pod_name} in namespace {namespace}: {e}")

        time.sleep(15)  # 每15秒更新一次

if __name__ == '__main__':
    start_http_server(9999)
    threading.Thread(target=collect_system_metrics, daemon=True).start()
    threading.Thread(target=collect_k8s_metrics, daemon=True).start()
    print("Metrics server started on port 9999")
    
    while True:
        time.sleep(60)  # 主线程保持运行
```

**Comment by zking2000** [comment]
```
from prometheus_client import start_http_server, Gauge, Counter
import os
import time
import threading
from kubernetes import client, config

# Kubernetes metrics
config.load_incluster_config()
v1 = client.CoreV1Api()

# 当前 Pod 和容器指标
container_cpu_usage = Gauge('container_cpu_usage', 'Container CPU usage in cores', ['container'])
container_memory_usage = Gauge('container_memory_usage', 'Container memory usage in bytes', ['container'])
container_restarts = Counter('container_restarts', 'Container restart count', ['container'])
container_ready = Gauge('container_ready', 'Container ready status', ['container'])
container_status = Gauge('container_status', 'Container status', ['container', 'status'])

# 获取当前 Pod 的名称和命名空间
current_pod_name = os.environ.get('HOSTNAME')
current_namespace = open("/var/run/secrets/kubernetes.io/serviceaccount/namespace").read()

def collect_current_pod_metrics():
    while True:
        try:
            pod_metrics = v1.read_namespaced_pod_status(name=current_pod_name, namespace=current_namespace)
            if pod_metrics.status and pod_metrics.status.container_statuses:
                for container_status in pod_metrics.status.container_statuses:
                    container_name = container_status.name
                    
                    # 容器 CPU 使用
                    if container_status.usage and container_status.usage.cpu:
                        cpu_usage_cores = int(container_status.usage.cpu) / 1e9  # 转换为核心数
                        container_cpu_usage.labels(container=container_name).set(cpu_usage_cores)

                    # 容器内存使用
                    if container_status.usage and container_status.usage.memory:
                        memory_usage_bytes = int(container_status.usage.memory)
                        container_memory_usage.labels(container=container_name).set(memory_usage_bytes)

                    # 容器重启次数
                    container_restarts.labels(container=container_name).inc(container_status.restart_count)

                    # 容器就绪状态
                    container_ready.labels(container=container_name).set(1 if container_status.ready else 0)

                    # 容器状态
                    for status_type, status_info in container_status.state.to_dict().items():
                        if status_info is not None:
                            container_status.labels(container=container_name, status=status_type).set(1)
                        else:
                            container_status.labels(container=container_name, status=status_type).set(0)

        except client.exceptions.ApiException as e:
            print(f"Error fetching metrics for current pod: {e}")

        time.sleep(15)  # 每15秒更新一次

if __name__ == '__main__':
    start_http_server(9999)
    threading.Thread(target=collect_current_pod_metrics, daemon=True).start()
    print(f"Metrics server started on port 9999 for pod {current_pod_name} in namespace {current_namespace}")
    
    while True:
        time.sleep(60)  # 主线程保持运行
```

**Comment by zking2000** [comment]
```
receivers:
  prometheus:
    config:
      scrape_configs:
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: true
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          target_label: __metrics_path__
          regex: (.+)
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: kubernetes_namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: kubernetes_pod_name

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheusremotewrite]
```
