### ISSUE TITLE
alert manager

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#85]
```
global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your_username'
  smtp_auth_password: 'your_password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'your_email@example.com'
    send_resolved: true

templates:
- '/etc/alertmanager/template/*.tmpl'
```

**Comment by zking2000** [comment]
```
{{ define "email.custom.html" }}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ template "__subject" . }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
            padding: 20px;
        }
        .alert {
            background-color: #f8d7da;
            border-color: #f5c6cb;
            color: #721c24;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid transparent;
            border-radius: 4px;
        }
        .resolved {
            background-color: #d4edda;
            border-color: #c3e6cb;
            color: #155724;
        }
        table {
            border-collapse: collapse;
            width: 100%;
        }
        th, td {
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #ddd;
        }
        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>{{ template "__subject" . }}</h1>
        
        {{ if gt (len .Alerts.Firing) 0 }}
        <h2>Alerts Firing ({{ .Alerts.Firing | len }})</h2>
        {{ range .Alerts.Firing }}
        <div class="alert">
            <h3>{{ .Labels.alertname }}</h3>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>Started at:</strong> {{ .StartsAt }}</p>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <h4>Labels:</h4>
            <table>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                {{ range .Labels.SortedPairs }}
                <tr>
                    <td>{{ .Name }}</td>
                    <td>{{ .Value }}</td>
                </tr>
                {{ end }}
            </table>
        </div>
        {{ end }}
        {{ end }}

        {{ if gt (len .Alerts.Resolved) 0 }}
        <h2>Alerts Resolved ({{ .Alerts.Resolved | len }})</h2>
        {{ range .Alerts.Resolved }}
        <div class="alert resolved">
            <h3>{{ .Labels.alertname }}</h3>
            <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
            <p><strong>Started at:</strong> {{ .StartsAt }}</p>
            <p><strong>Ended at:</strong> {{ .EndsAt }}</p>
            <p><strong>Description:</strong> {{ .Annotations.description }}</p>
            <h4>Labels:</h4>
            <table>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
                {{ range .Labels.SortedPairs }}
                <tr>
                    <td>{{ .Name }}</td>
                    <td>{{ .Value }}</td>
                </tr>
                {{ end }}
            </table>
        </div>
        {{ end }}
        {{ end }}
    </div>
</body>
</html>
{{ end }}

{{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
```

**Comment by zking2000** [comment]
```
global:
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your_username'
  smtp_auth_password: 'your_password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'your_email@example.com'
    send_resolved: true
    html: '{{ template "email.custom.html" . }}'
    headers:
      subject: '{{ template "__subject" . }}'

templates:
- 'email.tmpl'

---
# Embedded email template
templates:
- |
  {{ define "email.custom.html" }}
  <!DOCTYPE html>
  <html>
  <head>
      <meta charset="UTF-8">
      <title>{{ template "__subject" . }}</title>
      <style>
          body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
          }
          .container {
              width: 80%;
              margin: auto;
              overflow: hidden;
              padding: 20px;
          }
          .alert {
              background-color: #f8d7da;
              border-color: #f5c6cb;
              color: #721c24;
              padding: 10px;
              margin-bottom: 15px;
              border: 1px solid transparent;
              border-radius: 4px;
          }
          .resolved {
              background-color: #d4edda;
              border-color: #c3e6cb;
              color: #155724;
          }
          table {
              border-collapse: collapse;
              width: 100%;
          }
          th, td {
              text-align: left;
              padding: 8px;
              border-bottom: 1px solid #ddd;
          }
          th {
              background-color: #f2f2f2;
          }
      </style>
  </head>
  <body>
      <div class="container">
          <h1>{{ template "__subject" . }}</h1>
          
          {{ if gt (len .Alerts.Firing) 0 }}
          <h2>Alerts Firing ({{ .Alerts.Firing | len }})</h2>
          {{ range .Alerts.Firing }}
          <div class="alert">
              <h3>{{ .Labels.alertname }}</h3>
              <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
              <p><strong>Started at:</strong> {{ .StartsAt }}</p>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <h4>Labels:</h4>
              <table>
                  <tr>
                      <th>Key</th>
                      <th>Value</th>
                  </tr>
                  {{ range .Labels.SortedPairs }}
                  <tr>
                      <td>{{ .Name }}</td>
                      <td>{{ .Value }}</td>
                  </tr>
                  {{ end }}
              </table>
          </div>
          {{ end }}
          {{ end }}

          {{ if gt (len .Alerts.Resolved) 0 }}
          <h2>Alerts Resolved ({{ .Alerts.Resolved | len }})</h2>
          {{ range .Alerts.Resolved }}
          <div class="alert resolved">
              <h3>{{ .Labels.alertname }}</h3>
              <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
              <p><strong>Started at:</strong> {{ .StartsAt }}</p>
              <p><strong>Ended at:</strong> {{ .EndsAt }}</p>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <h4>Labels:</h4>
              <table>
                  <tr>
                      <th>Key</th>
                      <th>Value</th>
                  </tr>
                  {{ range .Labels.SortedPairs }}
                  <tr>
                      <td>{{ .Name }}</td>
                      <td>{{ .Value }}</td>
                  </tr>
                  {{ end }}
              </table>
          </div>
          {{ end }}
          {{ end }}
      </div>
  </body>
  </html>
  {{ end }}

  {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
```

**Comment by zking2000** [comment]
```
global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: 'your_username'
  smtp_auth_password: 'your_password'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'your_email@example.com'
    send_resolved: true
    html: '{{ template "email.custom.html" . }}'
    headers:
      subject: '{{ template "__subject" . }}'

templates:
- '/etc/alertmanager/template/*.tmpl'

# Integrated email template
# This is placed at the end of the file
# Indentation is crucial in YAML, ensure it's correct
alertmanager_config: |
  {{ define "email.custom.html" }}
  <!DOCTYPE html>
  <html>
  <head>
      <meta charset="UTF-8">
      <title>{{ template "__subject" . }}</title>
      <style>
          body {
              font-family: Arial, sans-serif;
              line-height: 1.6;
              color: #333;
          }
          .container {
              width: 80%;
              margin: auto;
              overflow: hidden;
              padding: 20px;
          }
          .alert {
              background-color: #f8d7da;
              border-color: #f5c6cb;
              color: #721c24;
              padding: 10px;
              margin-bottom: 15px;
              border: 1px solid transparent;
              border-radius: 4px;
          }
          .resolved {
              background-color: #d4edda;
              border-color: #c3e6cb;
              color: #155724;
          }
          table {
              border-collapse: collapse;
              width: 100%;
          }
          th, td {
              text-align: left;
              padding: 8px;
              border-bottom: 1px solid #ddd;
          }
          th {
              background-color: #f2f2f2;
          }
      </style>
  </head>
  <body>
      <div class="container">
          <h1>{{ template "__subject" . }}</h1>
          
          {{ if gt (len .Alerts.Firing) 0 }}
          <h2>Alerts Firing ({{ .Alerts.Firing | len }})</h2>
          {{ range .Alerts.Firing }}
          <div class="alert">
              <h3>{{ .Labels.alertname }}</h3>
              <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
              <p><strong>Started at:</strong> {{ .StartsAt }}</p>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <h4>Labels:</h4>
              <table>
                  <tr>
                      <th>Key</th>
                      <th>Value</th>
                  </tr>
                  {{ range .Labels.SortedPairs }}
                  <tr>
                      <td>{{ .Name }}</td>
                      <td>{{ .Value }}</td>
                  </tr>
                  {{ end }}
              </table>
          </div>
          {{ end }}
          {{ end }}

          {{ if gt (len .Alerts.Resolved) 0 }}
          <h2>Alerts Resolved ({{ .Alerts.Resolved | len }})</h2>
          {{ range .Alerts.Resolved }}
          <div class="alert resolved">
              <h3>{{ .Labels.alertname }}</h3>
              <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
              <p><strong>Started at:</strong> {{ .StartsAt }}</p>
              <p><strong>Ended at:</strong> {{ .EndsAt }}</p>
              <p><strong>Description:</strong> {{ .Annotations.description }}</p>
              <h4>Labels:</h4>
              <table>
                  <tr>
                      <th>Key</th>
                      <th>Value</th>
                  </tr>
                  {{ range .Labels.SortedPairs }}
                  <tr>
                      <td>{{ .Name }}</td>
                      <td>{{ .Value }}</td>
                  </tr>
                  {{ end }}
              </table>
          </div>
          {{ end }}
          {{ end }}
      </div>
  </body>
  </html>
  {{ end }}

  {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
```

**Comment by zking2000** [comment]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring  # adjust if you're using a different namespace
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.example.com:587'
      smtp_from: 'alertmanager@example.com'
      smtp_auth_username: 'your_username'
      smtp_auth_password: 'your_password'
      smtp_require_tls: true

    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'email-notifications'

    receivers:
    - name: 'email-notifications'
      email_configs:
      - to: 'your_email@example.com'
        send_resolved: true
        html: '{{ template "email.custom.html" . }}'
        headers:
          subject: '{{ template "__subject" . }}'

    templates:
    - '/etc/alertmanager/templates/*.tmpl'

  email.tmpl: |
    {{ define "email.custom.html" }}
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{{ template "__subject" . }}</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                color: #333;
            }
            .container {
                width: 80%;
                margin: auto;
                overflow: hidden;
                padding: 20px;
            }
            .alert {
                background-color: #f8d7da;
                border-color: #f5c6cb;
                color: #721c24;
                padding: 10px;
                margin-bottom: 15px;
                border: 1px solid transparent;
                border-radius: 4px;
            }
            .resolved {
                background-color: #d4edda;
                border-color: #c3e6cb;
                color: #155724;
            }
            table {
                border-collapse: collapse;
                width: 100%;
            }
            th, td {
                text-align: left;
                padding: 8px;
                border-bottom: 1px solid #ddd;
            }
            th {
                background-color: #f2f2f2;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>{{ template "__subject" . }}</h1>
            
            {{ if gt (len .Alerts.Firing) 0 }}
            <h2>Alerts Firing ({{ .Alerts.Firing | len }})</h2>
            {{ range .Alerts.Firing }}
            <div class="alert">
                <h3>{{ .Labels.alertname }}</h3>
                <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
                <p><strong>Started at:</strong> {{ .StartsAt }}</p>
                <p><strong>Description:</strong> {{ .Annotations.description }}</p>
                <h4>Labels:</h4>
                <table>
                    <tr>
                        <th>Key</th>
                        <th>Value</th>
                    </tr>
                    {{ range .Labels.SortedPairs }}
                    <tr>
                        <td>{{ .Name }}</td>
                        <td>{{ .Value }}</td>
                    </tr>
                    {{ end }}
                </table>
            </div>
            {{ end }}
            {{ end }}

            {{ if gt (len .Alerts.Resolved) 0 }}
            <h2>Alerts Resolved ({{ .Alerts.Resolved | len }})</h2>
            {{ range .Alerts.Resolved }}
            <div class="alert resolved">
                <h3>{{ .Labels.alertname }}</h3>
                <p><strong>Severity:</strong> {{ .Labels.severity }}</p>
                <p><strong>Started at:</strong> {{ .StartsAt }}</p>
                <p><strong>Ended at:</strong> {{ .EndsAt }}</p>
                <p><strong>Description:</strong> {{ .Annotations.description }}</p>
                <h4>Labels:</h4>
                <table>
                    <tr>
                        <th>Key</th>
                        <th>Value</th>
                    </tr>
                    {{ range .Labels.SortedPairs }}
                    <tr>
                        <td>{{ .Name }}</td>
                        <td>{{ .Value }}</td>
                    </tr>
                    {{ end }}
                </table>
            </div>
            {{ end }}
            {{ end }}
        </div>
    </body>
    </html>
    {{ end }}

    {{ define "__subject" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}{{ end }}
```

**Comment by zking2000** [comment]
要实现您的需求，我们需要配置 Mimir 的告警规则、设置 Alertmanager，并确保它们正确集成。以下是详细的步骤：

1. 配置 Mimir 告警规则

首先，我们需要在 Mimir 中创建一个告警规则来检测 pod 是否处于 down 状态。



```yaml
namespace: kubernetes
name: pod_alerts
rules:
  - alert: PodDown
    expr: up{job="kubernetes-pods"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      summary: "Pod {{ $labels.pod }} is down"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been down for more than 5 minutes."

```

要应用这个规则：

a. 将此规则保存为一个 YAML 文件，例如 `pod_down_alert.yaml`。

b. 使用 Mimir 的 API 来加载规则：

```bash
curl -X POST http://<mimir-host>:8080/api/v1/rules/kubernetes \
  -H "Content-Type: application/yaml" \
  --data-binary @pod_down_alert.yaml
```

替换 `<mimir-host>` 为您的 Mimir 实例地址。

2. 配置 Alertmanager

接下来，我们需要配置 Alertmanager 来处理和路由这些告警。



```yaml
global:
  resolve_timeout: 5m

route:
  group_by: ['namespace']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'email-notifications'

receivers:
- name: 'email-notifications'
  email_configs:
  - to: 'your-email@example.com'
    from: 'alertmanager@example.com'
    smarthost: 'smtp.example.com:587'
    auth_username: 'your-username'
    auth_identity: 'your-username'
    auth_password: 'your-password'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'namespace']

```

要应用此配置：

a. 将配置保存为 `alertmanager.yml`。

b. 使用此配置文件启动 Alertmanager：

```bash
alertmanager --config.file=alertmanager.yml
```

3. 配置 Mimir 以使用 Alertmanager

确保 Mimir 知道如何与 Alertmanager 通信。在 Mimir 的配置文件中添加或修改以下内容：

```yaml
alertmanager:
  external_url: http://<alertmanager-host>:9093

```

替换 `<alertmanager-host>` 为您的 Alertmanager 实例地址。

4. 验证配置

a. 重启 Mimir 和 Alertmanager 服务以应用新的配置。

b. 可以通过手动停止一个 pod 来测试告警是否正常工作。

c. 检查 Alertmanager 的 Web UI（通常在 `http://<alertmanager-host>:9093`）以查看告警状态。

d. 验证是否收到了告警邮件。

注意事项：
- 确保您的 Kubernetes 集群正确暴露了 `up` 指标。
- 调整告警规则中的 `for` 持续时间以适应您的需求。
- 在生产环境中，建议使用更安全的方式存储敏感信息，如邮件服务器凭证。
- 考虑添加更多的告警规则来监控其他关键指标。

如果您需要进一步的帮助，例如如何调整告警规则、配置更复杂的路由逻辑，或者集成其他通知方式（如 Slack、PagerDuty 等），请告诉我。我很乐意提供更详细的指导。

**Comment by zking2000** [comment]
理解您想要修改这个特定的表达式。让我们根据您提供的信息来调整告警规则，使其更加精确地针对 "db-gateway" 容器。

以下是基于您提供的 `container_ready` 指标和标签修改后的告警规则：



```yaml
namespace: kubernetes
name: db_gateway_alerts
rules:
  - alert: DBGatewayContainerNotReady
    expr: container_ready{instance="localhost:9999", container="db-gateway"} == 0
    for: 5m
    labels:
      severity: critical
      service: db-gateway
    annotations:
      summary: "DB Gateway container is not ready"
      description: "The DB Gateway container has been in a not ready state for more than 5 minutes."
      instance: "{{ $labels.instance }}"

```

这个规则的解释：

1. `expr: container_ready{instance="localhost:9999", container="db-gateway"} == 0`: 
   - 这个表达式精确匹配 `instance` 为 "localhost:9999" 且 `container` 为 "db-gateway" 的指标。
   - 当这个指标的值为 0 时，表示容器不处于就绪状态。

2. `for: 5m`: 只有当容器持续 5 分钟不就绪时才触发告警。

3. 添加了额外的标签 `service: db-gateway`，这可以帮助在 Alertmanager 中进行更精细的路由和分组。

4. 在注解中包含了 `instance` 信息，这有助于快速定位问题。

要应用这个规则：

1. 将上述内容保存为一个 YAML 文件，例如 `db_gateway_alert.yaml`。

2. 使用 Mimir 的 API 来加载规则：

```bash
curl -X POST http://<mimir-host>:8080/api/v1/rules/kubernetes \
  -H "Content-Type: application/yaml" \
  --data-binary @db_gateway_alert.yaml
```

替换 `<mimir-host>` 为您的 Mimir 实例地址。

3. 确保 Alertmanager 配置能够正确处理这个新的告警。您可能想要为 db-gateway 服务添加特定的路由规则。例如：



```yaml
route:
  receiver: 'default-receiver'
  routes:
    - match:
        service: db-gateway
      receiver: 'db-team'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'general-alerts@example.com'
- name: 'db-team'
  email_configs:
  - to: 'db-team@example.com'

```

4. 验证配置：
   - 检查 Mimir 的规则 API 以确保规则已被正确加载：
     ```
     curl http://<mimir-host>:8080/api/v1/rules
     ```
   - 您可以临时修改 db-gateway 容器的就绪探针使其失败，来测试告警是否正常触发。
   - 检查 Alertmanager 的 Web UI 以查看告警状态。

注意事项：
1. 确保 `localhost:9999` 确实是您想要监控的实例。在生产环境中，这可能需要替换为实际的主机名或 IP 地址。

2. 考虑添加一个恢复告警：

```yaml
  - alert: DBGatewayContainerBackToReady
    expr: container_ready{instance="localhost:9999", container="db-gateway"} == 1
    for: 1m
    labels:
      severity: info
      service: db-gateway
    annotations:
      summary: "DB Gateway container is back to ready state"
      description: "The DB Gateway container has recovered and is now in a ready state."
      instance: "{{ $labels.instance }}"
```

3. 如果 `db-gateway` 是关键服务，您可能想要缩短 `for` 持续时间，例如改为 2 分钟或更短。

4. 考虑添加更多的上下文信息到告警中，比如相关的日志查询链接或故障排除指南。

如果您需要进一步的帮助，比如如何在 Grafana 中创建相关的仪表板，或者如何设置更复杂的告警逻辑（例如考虑多个指标），请随时告诉我。我很乐意提供更多指导。

**Comment by zking2000** [comment]
您提出了一个很好的问题。在这种情况下，`service` 标签并不是指 Kubernetes 的 Service 对象，而是我们为了告警分类而自定义的标签。对于 sidecar 容器（如 cloudsqlproxy）这种没有暴露 Service 的情况，我们可以直接基于容器名称来设置告警。让我为您创建一个针对 cloudsqlproxy sidecar 容器的告警规则。



```yaml
namespace: kubernetes
name: sidecar_alerts
rules:
  - alert: CloudSQLProxyNotReady
    expr: sum by(namespace, pod) (kube_pod_container_status_ready{container="cloudsqlproxy"} == 0)
    for: 5m
    labels:
      severity: critical
      component: cloudsqlproxy
    annotations:
      summary: "CloudSQL Proxy sidecar is not ready in pod {{ $labels.pod }}"
      description: "The CloudSQL Proxy sidecar container in pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has been in a not ready state for more than 5 minutes."

```

这个规则的解释：

1. `expr: sum by(namespace, pod) (kube_pod_container_status_ready{container="cloudsqlproxy"} == 0)`:
   - 这个表达式查找名为 "cloudsqlproxy" 的容器，其就绪状态为 0（即不就绪）。
   - `sum by(namespace, pod)` 确保我们每个不就绪的 pod 只触发一次告警。

2. `for: 5m`: 只有当容器持续 5 分钟不就绪时才触发告警。

3. 标签 `component: cloudsqlproxy` 用于在 Alertmanager 中进行路由和分组。

4. 注解中包含了 pod 和 namespace 信息，有助于快速定位问题。

应用这个规则的步骤：

1. 将上述内容保存为 YAML 文件，例如 `cloudsqlproxy_alert.yaml`。

2. 使用 Mimir 的 API 加载规则：

```bash
curl -X POST http://<mimir-host>:8080/api/v1/rules/kubernetes \
  -H "Content-Type: application/yaml" \
  --data-binary @cloudsqlproxy_alert.yaml
```

3. 在 Alertmanager 中添加相应的路由规则：



```yaml
route:
  receiver: 'default-receiver'
  routes:
    - match:
        component: cloudsqlproxy
      receiver: 'database-team'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'general-alerts@example.com'
- name: 'database-team'
  email_configs:
  - to: 'database-team@example.com'

```

注意事项：

1. 确保您的监控系统正在收集 `kube_pod_container_status_ready` 指标。这通常由 kube-state-metrics 提供。

2. 验证 "cloudsqlproxy" 确实是您的 CloudSQL Proxy sidecar 容器的名称。如果不是，请相应地调整规则。

3. 考虑添加更多上下文信息到告警中，比如相关的日志查询链接或故障排除步骤。

4. 您可能还想添加一个恢复告警，当 CloudSQL Proxy 恢复就绪状态时通知您：

```yaml
  - alert: CloudSQLProxyBackToReady
    expr: sum by(namespace, pod) (kube_pod_container_status_ready{container="cloudsqlproxy"} == 1)
    for: 1m
    labels:
      severity: info
      component: cloudsqlproxy
    annotations:
      summary: "CloudSQL Proxy sidecar is back to ready state in pod {{ $labels.pod }}"
      description: "The CloudSQL Proxy sidecar container in pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has recovered and is now in a ready state."
```

5. 如果您有多个使用 CloudSQL Proxy 的应用，可能需要添加额外的标签来区分不同的应用或数据库实例。

如果您需要进一步的帮助，比如如何监控 CloudSQL Proxy 的具体性能指标，或者如何设置更复杂的告警逻辑（例如考虑连接数或延迟），请随时告诉我。我很乐意提供更多指导。
