### ISSUE TITLE
jaeger

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#89]
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: jaeger
  labels:
    app: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 14250
          name: grpc
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - port: 16686
    name: ui
  - port: 14250
    name: grpc

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:latest
        ports:
        - containerPort: 4317
        - containerPort: 4318
        volumeMounts:
        - name: otel-collector-config
          mountPath: /etc/otel-collector
      volumes:
      - name: otel-collector-config
        configMap:
          name: otel-collector-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: jaeger
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      jaeger:
        endpoint: jaeger:14250
        tls:
          insecure: true

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [jaeger]

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: jaeger
spec:
  selector:
    app: otel-collector
  ports:
  - port: 4317
    name: grpc
  - port: 4318
    name: http
```
