### ISSUE TITLE
kafka

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#90]
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    listeners=SASL_PLAINTEXT://:9092
    advertised.listeners=SASL_PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092
    security.inter.broker.protocol=SASL_PLAINTEXT
    sasl.mechanism.inter.broker.protocol=PLAIN
    sasl.enabled.mechanisms=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_BROKER_USER}" \
        password="${KAFKA_BROKER_PASSWORD}";
    zookeeper.connect=${ZOOKEEPER_CONNECT}
    zookeeper.set.acl=true

  kafka_server_jaas.conf: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_BROKER_USER}"
        password="${KAFKA_BROKER_PASSWORD}"
        user_admin="${KAFKA_ADMIN_PASSWORD}"
        user_alice="${KAFKA_ALICE_PASSWORD}";
    };
    Client {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_CLIENT_USER}"
        password="${KAFKA_CLIENT_PASSWORD}";
    };

  client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_CLIENT_USER}" \
        password="${KAFKA_CLIENT_PASSWORD}";

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
stringData:
  broker-user: admin
  broker-password: admin-secret
  admin-password: admin-secret
  alice-password: alice-secret
  client-user: alice
  client-password: alice-secret

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
        - name: KAFKA_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: broker-user
        - name: KAFKA_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: broker-password
        - name: KAFKA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: admin-password
        - name: KAFKA_ALICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: alice-password
        - name: KAFKA_CLIENT_USER
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: client-user
        - name: KAFKA_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: client-password
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
      volumes:
      - name: config
        configMap:
          name: kafka-config

```

**Comment by zking2000** [comment]
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    listeners=SASL_PLAINTEXT://:9092
    advertised.listeners=SASL_PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092
    security.inter.broker.protocol=SASL_PLAINTEXT
    sasl.mechanism.inter.broker.protocol=PLAIN
    sasl.enabled.mechanisms=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_BROKER_USER}" \
        password="${KAFKA_BROKER_PASSWORD}";
    zookeeper.connect=${ZOOKEEPER_CONNECT}
    zookeeper.set.acl=true
    zookeeper.sasl.client=true
    zookeeper.sasl.clientconfig=Client

  kafka_server_jaas.conf: |
    KafkaServer {
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="${KAFKA_BROKER_USER}"
        password="${KAFKA_BROKER_PASSWORD}"
        user_admin="${KAFKA_ADMIN_PASSWORD}"
        user_alice="${KAFKA_ALICE_PASSWORD}";
    };
    Client {
        org.apache.zookeeper.server.auth.DigestLoginModule required
        username="${ZOOKEEPER_USER}"
        password="${ZOOKEEPER_PASSWORD}";
    };

  client.properties: |
    security.protocol=SASL_PLAINTEXT
    sasl.mechanism=PLAIN
    sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
        username="${KAFKA_CLIENT_USER}" \
        password="${KAFKA_CLIENT_PASSWORD}";

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
type: Opaque
stringData:
  broker-user: admin
  broker-password: admin-secret
  admin-password: admin-secret
  alice-password: alice-secret
  client-user: alice
  client-password: alice-secret
  zookeeper-user: zookeeper-user
  zookeeper-password: zookeeper-password

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: KAFKA_ADVERTISED_HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
        - name: KAFKA_BROKER_USER
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: broker-user
        - name: KAFKA_BROKER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: broker-password
        - name: KAFKA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: admin-password
        - name: KAFKA_ALICE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: alice-password
        - name: KAFKA_CLIENT_USER
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: client-user
        - name: KAFKA_CLIENT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: client-password
        - name: ZOOKEEPER_CONNECT
          value: "zookeeper-service:2181"
        - name: ZOOKEEPER_USER
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: zookeeper-user
        - name: ZOOKEEPER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: zookeeper-password
        volumeMounts:
        - name: config
          mountPath: /etc/kafka
      volumes:
      - name: config
        configMap:
          name: kafka-config

```

**Comment by zking2000** [comment]
https://www.micoder.cc/blog/2282.html

**Comment by zking2000** [comment]
https://www.cnblogs.com/hengchaoyue/articles/15302626.html

**Comment by zking2000** [comment]
```
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-0-ilb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-0
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1-ilb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-1
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-2-ilb
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  ports:
  - port: 9092
  selector:
    statefulset.kubernetes.io/pod-name: kafka-2
```





```
# 将现有的listeners配置注释掉或删除
# listeners=PLAINTEXT://your.host.name:9092

# 添加新的SASL_PLAINTEXT监听器
listeners=SASL_PLAINTEXT://:9092
advertised.listeners=SASL_PLAINTEXT://${KAFKA_ADVERTISED_HOST_NAME}:9092

# 设置安全协议
security.inter.broker.protocol=SASL_PLAINTEXT

# 配置SASL机制和JAAS配置文件
sasl.mechanism.inter.broker.protocol=PLAIN
sasl.enabled.mechanisms=PLAIN

# 指定JAAS配置文件路径
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="${KAFKA_BROKER_USER}" \
    password="${KAFKA_BROKER_PASSWORD}";

# Zookeeper连接配置
zookeeper.connect=${ZOOKEEPER_CONNECT}
zookeeper.set.acl=true

# 添加以下行来指定Zookeeper的SASL配置
zookeeper.sasl.client=true
zookeeper.sasl.clientconfig=Client

# 添加以下配置
listener.security.protocol.map=SASL_PLAINTEXT:SASL_PLAINTEXT
inter.broker.listener.name=SASL_PLAINTEXT

```
