### ISSUE TITLE
haproxy

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#91]
```
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode tcp
    option tcplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend kafka_frontend
    bind *:9093
    mode tcp
    default_backend kafka_backend

backend kafka_backend
    mode tcp
    balance roundrobin
    option tcp-check
    server kafka1 <kafka1_ip>:9093 check
    server kafka2 <kafka2_ip>:9093 check
    server kafka3 <kafka3_ip>:9093 check

```

**Comment by zking2000** [comment]
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: init-plaintext-external
        image: busybox
        command: ['/bin/sh', '-c']
        args:
        - |
          HOSTNAME=$(hostname)
          case $HOSTNAME in
            "kafka-0")
              PLAINTEXT_EXTERNAL="192.168.64.28"
              ;;
            "kafka-1")
              PLAINTEXT_EXTERNAL="192.168.64.29"
              ;;
            "kafka-2")
              PLAINTEXT_EXTERNAL="192.168.64.30"
              ;;
            *)
              echo "未知的主机名: $HOSTNAME"
              exit 1
              ;;
          esac
          echo $PLAINTEXT_EXTERNAL > /config/plaintext_external
        volumeMounts:
        - name: config
          mountPath: /config
      containers:
      - name: kafka
        image: your-kafka-image:tag
        env:
        - name: PLAINTEXT_EXTERNAL
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: plaintext_external
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

```
