### ISSUE TITLE
kafka

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#92]
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-exporter-config
  namespace: mq
data:
  config.yaml: |
    lowercaseOutputName: true
    rules:
    - pattern: "kafka.server<type=(.+), name=(.+)><>Value"
      name: kafka_server_$1_$2
    - pattern: "kafka.controller<type=(.+), name=(.+)><>Value"
      name: kafka_controller_$1_$2

```

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka
  namespace: mq
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: metrics
```

```
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  namespace: mq
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
  - name: metrics
    port: 9404
    targetPort: metrics

```

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: "kafka"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      initContainers:
      - name: setup-jmx-exporter
        image: busybox
        command: ['sh', '-c', 'wget -O /opt/jmx-exporter/jmx_prometheus_javaagent.jar https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.1/jmx_prometheus_javaagent-0.16.1.jar']
        volumeMounts:
        - name: jmx-jar
          mountPath: /opt/jmx-exporter
      containers:
      - name: kafka
        image: your-kafka-image:tag
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://:9092,EXTERNAL://$(POD_NAME).kafka-headless.default.svc.cluster.local:9093
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092,EXTERNAL://:9093
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: PLAINTEXT
        - name: EXTERNAL_IP
          value: |
            case ${POD_NAME} in
              kafka-0)
                echo "192.168.64.28"
                ;;
              kafka-1)
                echo "192.168.64.29"
                ;;
              kafka-2)
                echo "192.168.64.30"
                ;;
              *)
                echo "Unknown pod name: ${POD_NAME}"
                exit 1
                ;;
            esac
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: "DEBUG"
        - name: KAFKA_LOG4J_LOGGERS
          value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
        - name: KAFKA_OPTS
          value: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9404:/opt/jmx-exporter/config.yaml"
        - name: JMX_PORT
          value: "5555"
        command:
        - /bin/bash
        - -c
        - |
          export EXTERNAL_IP=$(eval "$EXTERNAL_IP")
          export KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://:9092,EXTERNAL://${EXTERNAL_IP}:9093"
          exec /docker-entrypoint.sh /run.sh
        ports:
        - containerPort: 9092
        - containerPort: 9093
        - containerPort: 9404
          name: metrics
        volumeMounts:
        - name: jmx-jar
          mountPath: /opt/jmx-exporter
        - name: jmx-config
          mountPath: /opt/jmx-exporter/config.yaml
          subPath: config.yaml
      - name: jmx-exporter
        image: bitnami/jmx-exporter:latest
        ports:
        - containerPort: 9404
        volumeMounts:
        - name: jmx-config
          mountPath: /opt/jmx-exporter/config.yaml
          subPath: config.yaml
      volumes:
      - name: jmx-jar
        emptyDir: {}
      - name: jmx-config
        configMap:
          name: kafka-jmx-exporter-config
  volumeClaimTemplates:
  - metadata:
      name: kafka-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
```

**Comment by zking2000** [comment]
```
# kafka-jmx-exporter-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-jmx-exporter-config
data:
  config.yaml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.server<type=(.+), name=(.+), topic=(.+)><>Value
        name: kafka_server_$1_$2
        labels:
          topic: "$3"
      - pattern: kafka.server<type=(.+), name=(.+)><>Value
        name: kafka_server_$1_$2
      - pattern: kafka.controller<type=(.+), name=(.+)><>Value
        name: kafka_controller_$1_$2
      - pattern: kafka.network<type=(.+), name=(.+)><>Value
        name: kafka_network_$1_$2
---
# kafka-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-headless
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9404"
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:latest
        ports:
        - containerPort: 9092
          name: kafka
        - containerPort: 9404
          name: jmx-exporter
        env:
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: EXTRA_ARGS
          value: "-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=9404:/opt/jmx-exporter/config.yaml"
        volumeMounts:
        - name: jmx-config
          mountPath: /opt/jmx-exporter/
      volumes:
      - name: jmx-config
        configMap:
          name: kafka-jmx-exporter-config
---
# kafka-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: kafka
  endpoints:
  - port: jmx-exporter
    interval: 30s
---
# kafka-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kafka-metrics
  labels:
    app: kafka
spec:
  ports:
  - name: jmx-exporter
    port: 9404
    targetPort: 9404
  selector:
    app: kafka
```
