### ISSUE TITLE
cassandra

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#96]
```
-- 创建键空间
CREATE KEYSPACE IF NOT EXISTS example_keyspace
WITH replication = {
    'class': 'SimpleStrategy',
    'replication_factor': 1
};

-- 使用键空间
USE example_keyspace;

-- 创建用户表
CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY,
    username text,
    email text,
    created_at timestamp,
    last_login timestamp
);

-- 插入数据
INSERT INTO users (user_id, username, email, created_at, last_login)
VALUES (uuid(), 'john_doe', 'john@example.com', toTimestamp(now()), toTimestamp(now()));

INSERT INTO users (user_id, username, email, created_at, last_login)
VALUES (uuid(), 'jane_doe', 'jane@example.com', toTimestamp(now()), toTimestamp(now()));

-- 查询数据
SELECT * FROM users;

-- 条件查询
SELECT * FROM users WHERE username = 'john_doe' ALLOW FILTERING;

-- 更新数据
UPDATE users 
SET last_login = toTimestamp(now())
WHERE user_id = [替换为实际 user_id];

-- 删除数据
DELETE FROM users WHERE user_id = [替换为实际 user_id];

-- 创建索引
CREATE INDEX ON users (username);

-- 创建带有集合的表
CREATE TABLE IF NOT EXISTS user_posts (
    user_id UUID,
    post_id timeuuid,
    title text,
    content text,
    tags set<text>,
    likes counter,
    PRIMARY KEY ((user_id), post_id)
) WITH CLUSTERING ORDER BY (post_id DESC);
```

```
from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
from datetime import datetime
import uuid

# 连接到集群
cluster = Cluster(['localhost'], port=9042)
session = cluster.connect()

# 创建键空间
session.execute("""
    CREATE KEYSPACE IF NOT EXISTS example_keyspace
    WITH replication = {
        'class': 'SimpleStrategy',
        'replication_factor': 1
    }
""")

# 使用键空间
session.set_keyspace('example_keyspace')

# 创建表
session.execute("""
    CREATE TABLE IF NOT EXISTS users (
        user_id uuid PRIMARY KEY,
        username text,
        email text,
        created_at timestamp
    )
""")

# 插入数据
user_id = uuid.uuid4()
session.execute("""
    INSERT INTO users (user_id, username, email, created_at)
    VALUES (%s, %s, %s, %s)
""", (user_id, "john_doe", "john@example.com", datetime.now()))

# 查询数据
rows = session.execute("SELECT * FROM users")
for row in rows:
    print(f"User: {row.username}, Email: {row.email}")

# 关闭连接
cluster.shutdown()
```

**Comment by zking2000** [comment]
```
# 创建 Secret 存储认证信息
apiVersion: v1
kind: Secret
metadata:
  name: cassandra-web-credentials
  namespace: cassandra
type: Opaque
data:
  username: Y2Fzc2FuZHJh  # base64 encoded 'cassandra'
  password: Y2Fzc2FuZHJh  # base64 encoded 'cassandra'
---
# 创建 ConfigMap 存储配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-web-config
  namespace: cassandra
data:
  CASSANDRA_HOST: "cassandra-service"  # 你的 Cassandra 服务名称
  CASSANDRA_PORT: "9042"
---
# 创建 Service
apiVersion: v1
kind: Service
metadata:
  name: cassandra-web
  namespace: cassandra
  labels:
    app: cassandra-web
spec:
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: cassandra-web
  type: ClusterIP
---
# 创建 Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cassandra-web
  namespace: cassandra
  labels:
    app: cassandra-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-web
  template:
    metadata:
      labels:
        app: cassandra-web
    spec:
      containers:
        - name: cassandra-web
          image: ipushc/cassandra-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: CASSANDRA_HOST
              valueFrom:
                configMapKeyRef:
                  name: cassandra-web-config
                  key: CASSANDRA_HOST
            - name: CASSANDRA_PORT
              valueFrom:
                configMapKeyRef:
                  name: cassandra-web-config
                  key: CASSANDRA_PORT
            - name: CASSANDRA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cassandra-web-credentials
                  key: username
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cassandra-web-credentials
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
---
# 创建 Ingress (如果需要外部访问)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cassandra-web-ingress
  namespace: cassandra
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: cassandra-web.example.com  # 替换为你的域名
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cassandra-web
                port:
                  number: 8083
```
