### ISSUE TITLE
Jaeger

### ISSUE THREAD

**Issue by zking2000** [zking2000/NotePad#98]
``` 

# 1. 创建命名空间
apiVersion: v1
kind: Namespace
metadata:
  name: observability

---
# 2. 创建采样策略的ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-sampling-config
  namespace: observability
data:
  sampling.json: |-
    {
      "default_strategy": {
        "type": "probabilistic",
        "param": 0.1
      },
      "service_strategies": [
        {
          "service": "important-service",
          "type": "probabilistic",
          "param": 0.5
        }
      ]
    }

---
# 3. Jaeger Operator 部署配置
apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger
  namespace: observability
spec:
  strategy: production
  sampling:
    options:
      default_strategy:
        type: probabilistic
        param: 0.1
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: http://elasticsearch:9200
  collector:
    options:
      kafka:
        producer:
          topic: jaeger-spans
        protocol: grpc
    samplingConfig:
      configMapName: jaeger-sampling-config
  query:
    options:
      query:
        base-path: /jaeger
  ingress:
    enabled: true
    hosts:
      - jaeger.example.com

---
# 4. 创建Service Account并授予必要权限
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jaeger-operator
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jaeger-operator
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments", "daemonsets"]
  verbs: ["*"]
- apiGroups: ["jaegertracing.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jaeger-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jaeger-operator
subjects:
- kind: ServiceAccount
  name: jaeger-operator
  namespace: observability

```
